server:
  port: 8091
  # 指定项目名
  #servlet:
  #context-path: /test
  tomcat:
    max-connections: 10000
    max-threads: 10000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db2022?useSSL=false&charset=utf8mb4&serverTimezone=Hongkong
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:  # Redis数据库索引（默认为0）
    database: '0'
    host: 127.0.0.1  #Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: 123123
    pool:
      max-active: 10000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10000 # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: qxxzbdx@163.com
    password: GBRAEGYBAQZDHYKZ
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.study.seckill.model
  #配置smtp服务器
email:
    #系统发件人邮箱
  system: qxxzbdx@163.com
  hr: 2578908933@qq.com
rocketmq:
  name-server: 101.201.31.118:9876
  producer:
    group: springbootGroup
  topic: seckill
  consumer:
    order:
      group: GID_order
      tags: order
    cache:
      group: GID_del_cache
      tags: delCache
http:
  maxTotal: 300
  defaultMaxPerRoute: 50
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
login:
  filter:
    pattern: '/demo/(\w)+'
    serviceId: 'service1'
    token:
      url: 'http://127.0.0.1:8080/user/checkUserToken'